const actionTypes={
   GET_PRODUCTIONS:'GET_PRODUCTIONS',
   GET_PRODUCTIONS_SUCCESS:'GET_PRODUCTIONS_SUCCESS',
   GET_PHOTOS:'GET_PHOTOS',
   GET_PHOTOS_SUCCESS:'GET_PHOTOS_SUCCESS'
}

export default actionTypes;